# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: .*/Baseline
      - id: end-of-file-fixer
        exclude: .*/Baseline
      - id: check-added-large-files
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.3
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: spicy-format
        name: spicy-format
        entry: spicy-format -i
        files: '.*.spicy$'
        language: system
